services:
  - type: web
    name: volleyball-predictions
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: volleyball-db
          property: connectionString

databases:
  - name: volleyball-db
    databaseName: volleyball_predictions
    user: volleyball_user